from .analisis_marca_service import get_analisis_marca
from .producto_service import get_consulta_producto
from .existencias_service import get_existencias_por_tienda
from .movimiento_service import get_movimiento, get_resumen_movimiento
from .faltantes_service import get_faltantes
from .reabastecimiento_service import get_reabastecimiento_avanzado
from .redistribucion_service import get_redistribucion_regional